# Дисциплина «Искусственный интеллект»

## Рабочая тетрадь №2

### Библиотеки

In [47]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

### Задание 1.3.1

In [5]:
x = np.ones((3,3))
x = np.zeros((8,8), dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Задание 1.3.2

In [12]:
matrix = np.zeros((5,5), dtype=int)
matrix += np.arange(5)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### Задание 1.3.3

In [15]:
res = np.random.random((3, 3, 3))
print(res)

[[[0.4213534  0.8161733  0.10680639]
  [0.14803219 0.0385316  0.89543018]
  [0.613683   0.39014721 0.60411926]]

 [[0.35879978 0.36127698 0.33924786]
  [0.24586196 0.75576637 0.12925481]
  [0.41177568 0.543191   0.14251116]]

 [[0.72743652 0.61183385 0.57880192]
  [0.00674983 0.41566982 0.96449558]
  [0.78062539 0.13657014 0.65422375]]]


### Задание 1.3.4

In [52]:
z = np.ones((5, 5), dtype=int)
z[1:-1,1:-1] = 0
print(z)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Задание 1.3.5

In [26]:
res = np.sort(np.random.random(10))
print(res)

[0.24078757 0.24367849 0.34442941 0.53335834 0.75949129 0.7775323
 0.85963456 0.86104558 0.89775055 0.9361196 ]


### Задание 1.3.6

In [29]:
matrix = np.random.random((10, 10))
print(np.shape(matrix))
print(np.ndim(matrix))
print(np.size(matrix))

(10, 10)
2
100


### Задание 2.3.1

In [33]:
a = pd.Series([2, 4, 6, 8])
b = pd.Series([1, 3, 5, 7])

print(sum((a - b)**2)**0.5)

2.0


### Задание 2.3.2

In [49]:
url = 'titanic.csv'
dataframe = pd.read_csv(url)
print(dataframe.head(5))

                                            Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0  


### Задание 2.3.3

In [43]:
print(dataframe.head(2))
print(dataframe.tail(3))
print(dataframe.shape)
print(dataframe.describe())
print(dataframe.iloc[1:4])
print(dataframe[dataframe['PClass'] == '1st'].head(2))

                           Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1
                  Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0
(1313, 6)
              Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000
                                            Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0

### Задание 3.2.3

In [50]:
url = 'iris.csv'
dataframe = pd.read_csv(url)
minmax_scaler = preprocessing.MinMaxScaler()
z_scaler = preprocessing.StandardScaler()
dataframe[['sepal_length_cm']] = minmax_scaler.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = z_scaler.fit_transform(dataframe[['sepal_width_cm']])
print(dataframe)

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145 